# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('difficulty', models.IntegerField()),
                ('family', models.CharField(max_length=256)),
            ],
        ),
    ]
