# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsmatrix', '0002_create_model_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='extra_credit_tokens',
            field=models.IntegerField(default=0),
        ),
    ]
