# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillsmatrix', '0003_create_model_DeveloperSkill'),
        ('skillsmatrix', '0003_developer_model_fix'),
    ]

    operations = [
    ]
