# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 00:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsmatrix', '0005_create_model_ExtraCreditTokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracredit',
            name='date_credited',
            field=models.DateField(auto_now_add=True, default=datetime.date(2016, 5, 24)),
            preserve_default=False,
        ),
    ]
