# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-21 00:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsmatrix', '0007_auto_20170119_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 1, 21)),
        ),
        migrations.AlterField(
            model_name='developerskill',
            name='proficiency',
            field=models.IntegerField(choices=[('0', 'Youngling'), ('1', 'Padawan'), ('2', 'Jedi')]),
        ),
    ]
