# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-21 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsmatrix', '0008_auto_20170121_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developerskill',
            name='proficiency',
            field=models.IntegerField(choices=[(1, 'Youngling'), (2, 'Padawan'), (3, 'Jedi')]),
        ),
    ]
