# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsmatrix', '0011_auto_20170123_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='developer',
            name='phone',
            field=models.CharField(blank=True, default='phone', max_length=10, null=True),
        ),
    ]
