# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsmatrix', '0012_auto_20170125_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='manager',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='developer',
            name='phone',
            field=models.CharField(blank=True, default='phone', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='title',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi',
            field=models.CharField(max_length=512),
        ),
    ]
