# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-15 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsmatrix', '0013_auto_20170125_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_url',
            field=models.CharField(default='', max_length=512),
        ),
    ]
