# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-17 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillsmatrix', '0014_auto_20170215_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerskill',
            name='has_skill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='developerskill',
            name='proficiency',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], null=True),
        ),
        migrations.AlterField(
            model_name='developerskill',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
