# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-20 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillsmatrix', '0016_auto_20170217_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_credited', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_lead',
        ),
        migrations.RemoveField(
            model_name='projectdeveloper',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='projectdeveloper',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectskill',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectskill',
            name='skill',
        ),
        migrations.AddField(
            model_name='developer',
            name='extra_credit_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='developer',
            name='phone',
            field=models.CharField(blank=True, default='(###) ###-####', max_length=512, null=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectDeveloper',
        ),
        migrations.DeleteModel(
            name='ProjectSkill',
        ),
        migrations.AddField(
            model_name='extracredit',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracredit_recipient', to='skillsmatrix.Developer'),
        ),
        migrations.AddField(
            model_name='extracredit',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracredit_sender', to='skillsmatrix.Developer'),
        ),
        migrations.AddField(
            model_name='extracredit',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracredit_skill', to='skillsmatrix.Skill'),
        ),
    ]
